import pandas as pd
import mysql.connector

# 1. Load the data generated by your BeautifulSoup script
csv_filepath = "/Users/kshitijmr13/Companies Market Share/companies_by_earnings.csv"
print("Reading BeautifulSoup CSV file...")
df = pd.read_csv(csv_filepath)

# 2. Establish connection to your local MySQL Server
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="yashmr13",  # Replace with your actual MySQL root password
    database="corporate_intelligence"
)
cursor = conn.cursor()

# 3. Define the parameterized bulk SQL query
insert_sql = """
    INSERT INTO raw_company_earnings 
    (company_rank, company_name, ticker, formatted_earnings, raw_earnings_numeric, stock_price_formatted, country_name) 
    VALUES (%s, %s, %s, %s, %s, %s, %s)
"""

# 4. Parse the DataFrame rows into standard tuple structures
batch_records = []
for _, row in df.iterrows():
    record = (
        int(row['Rank']),
        str(row['Company Name']),
        str(row['Ticker']),
        str(row['Earnings']),
        int(row['Raw Earnings ($)']) if pd.notna(row['Raw Earnings ($)']) else None,
        str(row['Stock Price']),
        str(row['Country'])
    )
    batch_records.append(record)

# 5. Execute transactional block transfer
print("Streaming records into MySQL staging table...")
cursor.executemany(insert_sql, batch_records)
conn.commit()

print(f"Success! Safely committed {cursor.rowcount} company records to MySQL database.")
cursor.close()
conn.close()